import React, { useState, useMemo } from 'react';
import { X, Palette, ImageIcon, ChevronRight, Save, Calendar, User, Layers, CheckCircle2, MessageSquare, Send, Search, ArrowLeft, Monitor, Trash2, Plus } from 'lucide-react';
import { ContentPost, MediaFile } from '../../../types';
import MediaLibraryView from '../../../pages/MediaLibraryView';
import { RichTextEditor } from '../../RichTextEditor';
import { useTheme } from '../../../contexts/ThemeContext';

interface ArtworkStudioEditorProps {
  post: ContentPost;
  onSave: (post: ContentPost) => void;
  onClose: () => void;
  mediaFiles: MediaFile[];
  onUploadMedia: (file: MediaFile) => void;
  allPosts: ContentPost[];
}

const ArtworkStudioEditor: React.FC<ArtworkStudioEditorProps> = ({ post, onSave, onClose, mediaFiles, onUploadMedia, allPosts }) => {
  const { theme, t } = useTheme();
  const [data, setData] = useState<ContentPost>(post);
  const [activeTab, setActiveTab] = useState<'editor' | 'preview'>('editor');
  const [showMediaModal, setShowMediaModal] = useState(false);
  const [selectionTarget, setSelectionTarget] = useState<{type: 'main' | 'gallery', index?: number}>({type: 'main'});
  const [showAuthorPicker, setShowAuthorPicker] = useState(false);
  const [authorSearch, setAuthorSearch] = useState('');
  const [showRequestForm, setShowRequestForm] = useState(false);
  const [requestSent, setRequestSent] = useState(false);
  const [requestForm, setRequestForm] = useState({ firstName: '', lastName: '', contact: '', message: '' });

  const handleMediaSelect = (file: MediaFile) => {
    if (selectionTarget.type === 'main') setData({ ...data, coverImage: file.url || '' });
    else if (selectionTarget.type === 'gallery') setData({ ...data, artworkMetadata: { ...data.artworkMetadata!, gallery: [...(data.artworkMetadata?.gallery || []), file.url || ''] } });
    setShowMediaModal(false);
  };

  const artists = useMemo(() => allPosts.filter(p => p.category === 'ARTISTS'), [allPosts]);
  const selectAuthor = (artist: ContentPost) => { setData({ ...data, artworkMetadata: { ...data.artworkMetadata!, author: { id: artist.id, name: artist.title || artist.name } } }); setShowAuthorPicker(false); };
  const handleSendRequest = (e: React.FormEvent) => { e.preventDefault(); setRequestSent(true); setTimeout(() => { setShowRequestForm(false); setRequestSent(false); }, 3000); };

  return (
    <div className="fixed inset-0 z-[100] bg-white flex flex-col overflow-hidden animate-fadeIn font-sans">
      <div className="h-16 border-b border-gray-100 flex items-center justify-between px-6 bg-white shrink-0 z-20 shadow-sm">
         <div className="flex items-center gap-4"><button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-full text-gray-500"><ArrowLeft size={20}/></button><div className="flex flex-col"><h2 className="text-sm font-black uppercase tracking-widest text-[#1A1A1A]">ARTWORK STUDIO</h2><p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest opacity-60">Loyiha: {data.title || 'Nomsiz'}</p></div></div>
         <div className="flex items-center gap-4"><div className="flex bg-gray-50 border border-gray-200 rounded-full p-0.5"><button onClick={() => setActiveTab('editor')} className={`px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest transition-all ${activeTab === 'editor' ? 'bg-[#176f6f] text-white shadow-md' : 'text-gray-400 hover:text-gray-600'}`}>Muharrir</button><button onClick={() => setActiveTab('preview')} className={`px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest transition-all ${activeTab === 'preview' ? 'bg-[#176f6f] text-white shadow-md' : 'text-gray-400 hover:text-gray-600'}`}>Preview</button></div><button onClick={() => onSave(data)} className="bg-[#176f6f] hover:bg-[#125757] text-white px-8 py-2 text-[10px] font-black uppercase tracking-[0.2em] shadow-lg flex items-center gap-2"><Save size={14}/> {t('save').toUpperCase()}</button></div>
      </div>
      <div className="flex-1 overflow-hidden flex">
         <div className={`flex-1 overflow-y-auto custom-scrollbar p-10 bg-[url('https://www.transparenttextures.com/patterns/cream-paper.png')] ${activeTab === 'preview' ? 'hidden' : 'block'}`}>
            <div className="max-w-4xl mx-auto space-y-12 pb-32">
               <div className="space-y-4"><label className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Asosiy Artwork Tasviri</label><div onClick={() => { setSelectionTarget({type: 'main'}); setShowMediaModal(true); }} className="aspect-[16/9] bg-white border-2 border-dashed border-gray-200 hover:border-[#176f6f] transition-all cursor-pointer relative overflow-hidden flex flex-col items-center justify-center text-center p-4 group shadow-sm">{data.coverImage ? (<img src={data.coverImage} className="absolute inset-0 w-full h-full object-cover filter sepia-[.1]" />) : (<Palette size={56} className="text-gray-200" />)}<div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center text-white text-[10px] font-black uppercase tracking-widest">Rasm tanlang</div></div></div>
               <div className="space-y-8">
                  <div className="space-y-2"><label className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">{t('artwork_name')}</label><input value={data.title} onChange={e => setData({...data, title: e.target.value, name: e.target.value})} placeholder="Artwork sarlavhasi..." className="w-full bg-transparent border-b-2 border-gray-200 py-3 text-5xl font-caslon font-bold text-[#1A1A1A] outline-none focus:border-[#176f6f] transition-all" /></div>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-8"><div className="space-y-2"><label className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">{t('author')}</label><button onClick={() => setShowAuthorPicker(true)} className="w-full bg-white border border-gray-200 p-3 text-sm font-bold text-left hover:bg-gray-50 flex items-center justify-between transition-colors"><span className="truncate">{data.artworkMetadata?.author?.name || 'Tanlang...'}</span><Plus size={14} className="text-gray-400" /></button></div><div className="space-y-2"><label className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">{t('year')}</label><input value={data.artworkMetadata?.year} onChange={e => setData({...data, artworkMetadata: {...data.artworkMetadata!, year: e.target.value}})} placeholder="202X" className="w-full bg-white border border-gray-200 p-3 text-sm font-bold outline-none focus:border-[#176f6f] transition-all" /></div><div className="space-y-2"><label className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">{t('city')}</label><input value={data.artworkMetadata?.location} onChange={e => setData({...data, artworkMetadata: {...data.artworkMetadata!, location: e.target.value}})} placeholder="Shahar, Mamlakat" className="w-full bg-white border border-gray-200 p-3 text-sm font-bold outline-none focus:border-[#176f6f] transition-all" /></div></div>
               </div>
               <div className="space-y-4"><label className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Artwork Haqida Maqola</label><RichTextEditor content={data.content || ''} onChange={c => setData({...data, content: c})} onRequestMedia={() => { setSelectionTarget({type: 'main'}); setShowMediaModal(true); }} /></div>
               <div className="space-y-6"><div className="flex items-center justify-between border-b border-gray-100 pb-2"><label className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Qo'shimcha Detallar (Galereya)</label><button onClick={() => { setSelectionTarget({type: 'gallery'}); setShowMediaModal(true); }} className="flex items-center gap-1 text-[10px] font-black text-accent uppercase tracking-widest hover:underline"><Plus size={14}/> Rasm qo'shish</button></div><div className="grid grid-cols-4 md:grid-cols-6 gap-4">{data.artworkMetadata?.gallery.map((url, idx) => (<div key={idx} className="aspect-square bg-gray-50 border border-gray-200 relative group overflow-hidden shadow-sm"><img src={url} className="w-full h-full object-cover" /><button onClick={() => setData({...data, artworkMetadata: {...data.artworkMetadata!, gallery: data.artworkMetadata!.gallery.filter((_, i) => i !== idx)}})} className="absolute top-1 right-1 p-1 bg-white/80 rounded shadow-sm opacity-0 group-hover:opacity-100 text-red-500 hover:text-red-700 transition-all"><Trash2 size={12}/></button></div>))}</div></div>
            </div>
         </div>
         <div className={`flex-1 bg-[#fcfbf7] overflow-y-auto custom-scrollbar ${activeTab === 'editor' ? 'hidden' : 'block'}`}>
            <div className="max-w-6xl mx-auto p-12 lg:p-24 space-y-24 font-serif animate-fadeIn">
               <section className="flex flex-col items-center"><div className="w-full max-w-4xl shadow-[0_50px_100px_-20px_rgba(0,0,0,0.25)] border-8 border-white overflow-hidden filter sepia-[.05] transition-transform duration-700 hover:scale-[1.01]">{data.coverImage ? (<img src={data.coverImage} className="w-full h-auto" />) : (<div className="aspect-[4/5] w-full flex items-center justify-center text-gray-200 bg-white"><Palette size={120}/></div>)}</div><div className="mt-20 text-center space-y-8 w-full max-w-3xl"><div className="flex items-center justify-center gap-4 text-accent font-sans text-xs font-bold uppercase tracking-[0.5em]"><span>ARTWORK</span><div className="w-1.5 h-1.5 rounded-full bg-accent/20"></div><span>CREATION</span></div><h1 className="text-7xl lg:text-9xl font-caslon text-[#1A1A1A] leading-none tracking-tighter">{data.title || 'Sarlavhasiz Artwork'}</h1><div className="flex items-center justify-center gap-8 text-2xl font-serif text-gray-400 italic"><span>{data.artworkMetadata?.author?.name || 'Muallif noma\'lum'}</span><span className="w-2 h-2 rounded-full bg-gray-200"></span><span>{data.artworkMetadata?.year || 'Sana yo\'q'}</span></div><div className="pt-10 flex flex-col items-center gap-6"><button onClick={() => setShowRequestForm(true)} className="bg-[#176f6f] text-white px-16 py-6 text-[12px] font-black uppercase tracking-[0.5em] shadow-2xl hover:bg-[#125757] transition-all transform hover:-translate-y-2 flex items-center justify-center gap-4">{t('request_artwork')}</button></div></div></section>
            </div>
         </div>
      </div>
      {showRequestForm && (<div className="fixed inset-0 z-[300] bg-black/80 backdrop-blur-lg flex items-center justify-center p-8"><div className="bg-white w-full max-w-2xl border border-gray-200 shadow-2xl p-12 animate-slideDown font-serif relative overflow-hidden"><div className="absolute top-0 left-0 w-full h-1.5 bg-[#176f6f]"></div><button onClick={() => setShowRequestForm(false)} className="absolute top-8 right-8 text-gray-400 hover:text-red-500 transition-colors"><X size={28}/></button>{requestSent ? (<div className="py-24 text-center space-y-8 animate-fadeIn"><div className="w-24 h-24 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center mx-auto border border-emerald-100"><CheckCircle2 size={56}/></div><div className="space-y-3"><h3 className="text-4xl font-caslon font-bold text-gray-900">{t('request_success')}</h3></div></div>) : (<form onSubmit={handleSendRequest} className="space-y-8"><div className="grid grid-cols-1 md:grid-cols-2 gap-8"><div className="space-y-2"><label className="text-[10px] font-black uppercase text-gray-400 tracking-widest">{t('name')}</label><input required value={requestForm.firstName} onChange={e => setRequestForm({...requestForm, firstName: e.target.value})} className="w-full bg-gray-50 border-b-2 border-gray-200 p-3 text-lg outline-none focus:border-[#176f6f] font-sans transition-all" /></div><div className="space-y-2"><label className="text-[10px] font-black uppercase text-gray-400 tracking-widest">{t('surname')}</label><input required value={requestForm.lastName} onChange={e => setRequestForm({...requestForm, lastName: e.target.value})} className="w-full bg-gray-50 border-b-2 border-gray-200 p-3 text-lg outline-none focus:border-[#176f6f] font-sans transition-all" /></div></div><div className="space-y-2"><label className="text-[10px] font-black uppercase text-gray-400 tracking-widest">{t('contact_info')}</label><input required value={requestForm.contact} onChange={e => setRequestForm({...requestForm, contact: e.target.value})} placeholder="Email yoki Tel" className="w-full bg-gray-50 border-b-2 border-gray-200 p-3 text-lg outline-none focus:border-[#176f6f] font-sans transition-all" /></div><button type="submit" className="w-full bg-[#176f6f] text-white py-5 font-black uppercase tracking-[0.4em] text-[12px] hover:bg-[#125757] transition-all shadow-2xl active:scale-[0.98] flex items-center justify-center gap-4">{t('send_request')} <Send size={18}/></button></form>)}</div></div>)}
      {showAuthorPicker && (<div className="fixed inset-0 z-[400] bg-black/60 backdrop-blur-md flex items-center justify-center p-8"><div className="bg-white w-full max-w-xl h-[80vh] border border-gray-200 shadow-2xl flex flex-col relative animate-slideDown overflow-hidden font-serif"><div className="h-16 border-b border-gray-100 flex items-center justify-between px-6 bg-gray-50/50"><h3 className="text-xl font-caslon font-bold uppercase tracking-widest text-[#176f6f]">Artistni bog'lash</h3><button onClick={() => setShowAuthorPicker(false)}><X size={24}/></button></div><div className="p-4 border-b border-gray-100"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" /><input value={authorSearch} onChange={e => setAuthorSearch(e.target.value)} placeholder="Artist qidirish..." className="w-full bg-gray-50 border border-gray-200 py-2 pl-10 pr-4 text-sm outline-none focus:border-accent font-sans" /></div></div><div className="flex-1 overflow-y-auto custom-scrollbar p-2">{artists.filter(a => (a.title || a.name || '').toLowerCase().includes(authorSearch.toLowerCase())).map(artist => (<div key={artist.id} onClick={() => selectAuthor(artist)} className={`flex items-center gap-4 p-3 border-b border-gray-50 cursor-pointer transition-colors ${data.artworkMetadata?.author?.id === artist.id ? 'bg-accent/5' : 'hover:bg-gray-50'}`}><div className="w-12 h-12 rounded-full bg-gray-100 overflow-hidden border border-gray-100">{artist.coverImage && <img src={artist.coverImage} className="w-full h-full object-cover" />}</div><div className="flex-1 min-w-0"><h4 className="font-bold text-sm text-textMain truncate">{artist.title || artist.name}</h4><p className="text-[10px] text-gray-400 font-sans uppercase">{artist.artistMetadata?.professions.join(', ')}</p></div>{data.artworkMetadata?.author?.id === artist.id && <Layers size={18} className="text-accent" />}</div>))}</div></div></div>)}
      {showMediaModal && (<div className="fixed inset-0 z-[500] bg-black/70 backdrop-blur-md flex items-center justify-center p-10"><div className="bg-white w-full max-w-5xl h-full border border-gray-200 shadow-2xl overflow-hidden relative"><button onClick={() => setShowMediaModal(false)} className="absolute top-4 right-4 z-50 p-2 bg-white rounded-full text-black shadow-xl hover:text-red-500 transition-all"><X size={24}/></button><MediaLibraryView files={mediaFiles} onUpload={onUploadMedia} isSelectMode={true} onSelect={handleMediaSelect} /></div></div>)}
    </div>
  );
};

export default ArtworkStudioEditor;