
import { NavItem, PageRoute, Article, VideoResource, Book, Creator, EventItem, Project, CreationItem, PortfolioItem } from './types';

export const HADITH_DATA = {
  arabic: "مَنْ سَلَكَ طَرِيقًا يَبْتَغِي فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ",
  uz: "“Kim ilm izlab yo‘lga chiqsa, Alloh unga jannat yo‘lini oson qiladi.”",
  en: "“Whoever follows a path in pursuit of knowledge, Allah will make easy for him a path to Paradise.”",
  ru: "“Кто вступил на путь поиска знаний, тому Аллах облегчит путь в Рай.”",
  tr: "“Kim ilim öğrenmek için bir yola girerse, Allah ona cennet yolunu kolaylaştırır.”",
  source: "Sahih Muslim (2699)"
};

export const TRANSLATIONS = {
  uz: {
    ilm: 'ILM',
    harakat: 'HARAKAT',
    ijod: 'IJOD',
    about: 'Biz Haqimizda',
    news: 'Xabarlar',
    support: 'Qo\'llab-Quvvatlash',
    contact: 'Aloqa',
    search: 'Qidiruv',
    menu: 'Menyu',
    settings: 'Sozlamalar',
    language: 'Til',
    theme: 'Mavzu',
    themeLight: 'Yorug\'',
    themeDark: 'Tungi',
    copyright: '© 2025 ME\'MOR. BARCHA HUQUQLAR HIMOAYALANGAN.',
    pillarsTitle: 'ASOSIY USTUNLAR',
    ilmTitle: 'ILM MASKANI',
    ilmDesc: 'Arxitektura va san\'atga oid ilmiy maqolalar, videodarslar va nodir manbalar jamlangan xazina.',
    ilmLink: 'KUTUBXONAGA KIRISH',
    amaliyotTitle: 'AMALIYOT MAYDONI',
    amaliyotDesc: 'Haqiqiy loyihalar, qurilish jarayonlari va ustoz-shogird an\'analarining zamonaviy ko\'rinishi.',
    amaliyotLink: 'LOYIHALARNI KO\'RISH',
    sanatTitle: 'RAQAMLI SAN\'AT',
    sanatDesc: 'Milliy naqshlarning vektor ko\'rinishlari, 3D modellar va zamonaviy dizayn elementlari.',
    sanatLink: 'GALEREYAGA O\'TISH',
    aboutTitle: 'ME\'MOR PLATFORMASI HAQIDA',
    aboutP1: 'Bizning maqsadimiz — unutilayotgan me\'morchilik an\'analarini zamonaviy raqamli texnologiyalar orqali qayta tiklash va kelajak avlodga bezavol yetkazishdir.',
    aboutP2: 'Bu yerda siz nafaqat nazariy bilim, balki usta-shogird an\'analari asosidagi amaliy tajribalarni ham topasiz.',
    teamTitle: 'JAMOA',
    teamDesc: 'Platforma ustida ishlayotgan mutaxassislar guruhi.',
    supportTitle: 'LOYIHANI QO\'LLAB-QUVVATLASH',
    supportDesc: '"Me\'mor" mustaqil platforma bo\'lib, siz kabi san\'at ixlosmandlari ko\'magida yashaydi.',
    supportFooter: 'Sizning yordamingiz — tariximizni saqlab qolishga qo\'shilgan hissa.',
    localCards: 'Mahalliy kartalar (Uzcard, Humo) orqali tezkor va qulay yordam.',
    intlCards: 'Xalqaro kartalar (Visa, MasterCard) orqali yordam berish.',
    sponsorButton: 'Homiylik Qilish',
    coffeeButton: 'Coffee Olib Berish',
    back: 'Ortga',
    notFound: 'Ma\'lumot topilmadi',
    ourTeam: 'Bizning Jamoa',
    // Action
    actionTitle: 'Harakat',
    actionDesc: 'Nazariyadan amaliyotga. Bizning loyihalarimiz va kelajak rejalari.',
    events: 'Tadbirlar',
    projects: 'Loyihalar',
    participate: 'Ishtirok etish',
    // News
    latestNews: 'So\'nggi Xabarlar',
    archive: 'Arxiv',
    readMoreNews: 'Batafsil o\'qish',
    // Creations
    creationTitle: 'Ijod Namunalari',
    creationDesc: 'Vektor naqshlar, konseptual dizaynlar va raqamli san\'at.',
    view: 'Ko\'rish',
    quote: '"Go\'zallik tafsilotlarda yashirin"',
    // Hadith
    hadithTitle: 'Ilm Fazilati',
    sources: 'Manbalar',
    hadithClose: 'Yopish',
    clickForFull: 'To\'liq matn uchun bosing',
    prophetName: 'Rasululloh ﷺ',
    readMore: 'Batafsil',
    // Detail Labels
    description: 'Tavsif',
    technicalDrawing: 'Texnik Chizma',
    materialTexture: 'Materiallar Fakturasi',
    specifications: 'Ma\'lumotlar',
    start: 'Boshlanish',
    type: 'Tur',
    scale: 'Hajm',
    team: 'Jamoa',
    experts: 'Ekspert',
    downloadFiles: 'Fayllarni yuklash',
    register: 'Ro\'yxatdan O\'tish',
    student: 'Shogird',
    experience: 'Tajriba',
    share: 'ULASHISH',
    author: 'Muallif',
    duration: 'Davomiyligi',
    // Home.tsx uchun yo'qolgan kalitlar
    harakatDesc: 'Haqiqiy loyihalar, qurilish jarayonlari va ustoz-shogird an\'analarining zamonaviy ko\'rinishi.',
    ijodDesc: 'Milliy naqshlarning vektor ko\'rinishlari, 3D modellar va zamonaviy dizayn elementlari.',
    knowledgeTreasury: 'Bilimlar Xazinasi',
    allArticles: 'Barcha Maqolalar',
    project: 'Loyiha',
    artGallery: 'San\'at Galereyasi',
    viewAll: 'Barchasini Ko\'rish',
    beautifyWorld: '"Dunyoni go\'zallashtirish uchun ..."',
    projectYear: 'ME\'MOR • 2025',
    teamMeeting: 'Jamoa Yig\'ilishi',
    seoHome: 'Bosh sahifa',
    seoKnowledge: 'Ilm Maskani',
    seoAction: 'Harakat',
    seoCreation: 'Ijod Namunalari',
    seoAbout: 'Biz Haqimizda',
    seoNews: 'Xabarlar',
    seoContact: 'Aloqa',
    seoSupport: 'Qo\'llab-Quvvatlash',
    seoSearch: 'Qidiruv',
    seoLogin: 'Kirish',
    seoRegister: 'Ro\'yxatdan O\'tish',
    // SEO Specifics
    seoHomeTitle: 'Me\'mor - O\'zbek milliy memorchiligi platformasi',
    seoHomeDesc: 'Me\'mor — O‘zbek memorchiligi, arxitektura va naqsh san’ati platformasi. Tarixiy meros va zamonaviy yechimlar uyg\'unligi.',
    seoIlmTitle: 'Ilm Maskani - Maqolalar, Videolar va Kitoblar',
    seoIlmDesc: 'Me\'mor platformasida arxitektura, san\'at va tarixga oid ilmiy manbalar, video darsliklar va nodir kitoblar to\'plami.',
    seoHarakatTitle: 'Harakat - Loyihalar va Tadbirlar',
    seoHarakatDesc: 'Me\'mor loyihalari, qurilish jarayonlari va bo\'lajak madaniy tadbirlar haqida ma\'lumotlar.',
    seoIjodTitle: 'Ijod Namunalari - Galereya',
    seoIjodDesc: 'Milliy va zamonaviy san\'at uyg\'unligi, vektor naqshlar, 3D modellar va kreativ ishlanmalar.',
    seoAboutTitle: 'Me\'mor Platformasi Haqida',
    seoAboutDesc: 'Me\'mor loyihasining maqsadi, qadriyatlari va ortidagi jamoa bilan tanishing.',
    seoContactTitle: 'Aloqa va Hamkorlik',
    seoContactDesc: 'Me\'mor jamoasi bilan bog\'lanish, hamkorlik takliflari va fikr-mulohazalar uchun.',
    seoNewsTitle: 'Yangiliklar va Voqealar',
    seoNewsDesc: 'Platformadagi so\'nggi o\'zgarishlar, yangi qo\'shilgan manbalar va muhim xabarlar.',
    seoSupportTitle: 'Loyihani Qo\'llab-Quvvatlash',
    seoSupportDesc: 'Me\'mor platformasi rivojiga hissa qo\'shing va milliy merosimizni saqlab qolishga yordam bering.',
    seeMore: 'Ko\'proq ma\'lumot'
  },
  en: {
    ilm: 'KNOWLEDGE',
    harakat: 'MOVEMENT',
    ijod: 'CREATION',
    about: 'About Us',
    news: 'News',
    support: 'Support',
    contact: 'Contact',
    search: 'Search',
    menu: 'Menu',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    copyright: '© 2025 ME\'MOR. ALL RIGHTS RESERVED.',
    pillarsTitle: 'CORE PILLARS',
    ilmTitle: 'HOUSE OF KNOWLEDGE',
    ilmDesc: 'A treasury of scientific articles, video lessons and rare sources on architecture and art.',
    ilmLink: 'ENTER LIBRARY',
    amaliyotTitle: 'FIELD OF PRACTICE',
    amaliyotDesc: 'Real projects, construction processes and a modern take on master-apprentice traditions.',
    amaliyotLink: 'VIEW PROJECTS',
    sanatTitle: 'DIGITAL ART',
    sanatDesc: 'Vector images of national patterns, 3D models and modern design elements.',
    sanatLink: 'GO TO GALLERY',
    aboutTitle: 'ABOUT ME\'MOR PLATFORM',
    aboutP1: 'Our goal is to revive forgotten architectural traditions through modern digital technologies and pass them on to future generations.',
    aboutP2: 'Here you will find not only theoretical knowledge, but also practical experience based on "master-apprentice" traditions.',
    teamTitle: 'TEAM',
    teamDesc: 'A group of specialists working on the platform.',
    supportTitle: 'PROJECT SUPPORT',
    supportDesc: '"Me\'mor" is an independent platform that lives with the help of art enthusiasts like you.',
    supportFooter: 'Your help is a contribution to preserving our history.',
    localCards: 'Fast and convenient support via local cards (Uzcard, Humo).',
    intlCards: 'Support via international cards (Visa, MasterCard).',
    sponsorButton: 'Become a Sponsor',
    coffeeButton: 'Buy Me a Coffee',
    back: 'Back',
    notFound: 'Information not found',
    ourTeam: 'Our Team',
    // Action
    actionTitle: 'Action',
    actionDesc: 'From theory to practice. Our projects and future plans.',
    events: 'Events',
    projects: 'Projects',
    participate: 'Participate',
    // News
    latestNews: 'Latest News',
    archive: 'Archive',
    readMoreNews: 'Read more',
    // Creations
    creationTitle: 'Creations',
    creationDesc: 'Vector patterns, conceptual designs, and digital art.',
    view: 'View',
    quote: '"Beauty is hidden in the details"',
    // Hadith
    hadithTitle: 'Virtue of Knowledge',
    sources: 'Sources',
    hadithClose: 'Close',
    clickForFull: 'Click for full text',
    prophetName: 'Prophet Muhammad ﷺ',
    readMore: 'Read More',
    // Detail Labels
    description: 'Description',
    technicalDrawing: 'Technical Drawing',
    materialTexture: 'Material Texture',
    specifications: 'Specifications',
    start: 'Start',
    type: 'Type',
    scale: 'Scale',
    team: 'Team',
    experts: 'Experts',
    downloadFiles: 'Download Files',
    register: 'Register',
    student: 'Student',
    experience: 'Experience',
    share: 'SHARE',
    author: 'Author',
    duration: 'Duration',
    // Missing keys from Home.tsx
    harakatDesc: 'Real projects, construction processes and a modern take on master-apprentice traditions.',
    ijodDesc: 'Vector images of national patterns, 3D models and modern design elements.',
    knowledgeTreasury: 'Treasury of Knowledge',
    allArticles: 'All Articles',
    project: 'Project',
    artGallery: 'Art Gallery',
    viewAll: 'View All',
    beautifyWorld: '"Dunyoni go\'zallashtirish uchun ..."',
    projectYear: 'ME\'MOR • 2025',
    teamMeeting: 'Team Meeting',
    seoHome: 'Home',
    seoKnowledge: 'House of Knowledge',
    seoAction: 'Action',
    seoCreation: 'Creations',
    seoAbout: 'About Us',
    seoNews: 'News',
    seoContact: 'Contact',
    seoSupport: 'Support',
    seoSearch: 'Search',
    seoLogin: 'Login',
    seoRegister: 'Register',
    // SEO Specifics
    seoHomeTitle: 'Me\'mor - Uzbek National Architecture Platform',
    seoHomeDesc: 'Me\'mor — Platform for Uzbek architecture, art, and patterns. Fusion of historical heritage and modern solutions.',
    seoIlmTitle: 'House of Knowledge - Articles, Videos & Books',
    seoIlmDesc: 'A collection of scientific resources, video tutorials, and rare books on architecture, art, and history at Me\'mor.',
    seoHarakatTitle: 'Action - Projects & Events',
    seoHarakatDesc: 'Information about Me\'mor projects, construction processes, and upcoming cultural events.',
    seoIjodTitle: 'Creations - Art Gallery',
    seoIjodDesc: 'Fusion of national and modern art, vector patterns, 3D models, and creative works.',
    seoAboutTitle: 'About Me\'mor Platform',
    seoAboutDesc: 'Learn about the mission, values, and the team behind the Me\'mor project.',
    seoContactTitle: 'Contact & Collaboration',
    seoContactDesc: 'Get in touch with the Me\'mor team for collaboration proposals and feedback.',
    seoNewsTitle: 'News & Events',
    seoNewsDesc: 'Latest updates from the platform, newly added resources, and important announcements.',
    seoSupportTitle: 'Support the Project',
    seoSupportDesc: 'Contribute to the development of the Me\'mor platform and help preserve our national heritage.',
    seeMore: 'See More'
  },
  ru: {
    ilm: 'НАУКА',
    harakat: 'ТЕЧЕНИЕ',
    ijod: 'ТВОРЕНИЕ',
    about: 'О нас',
    news: 'Новости',
    support: 'Поддержка',
    contact: 'Контакты',
    search: 'Поиск',
    menu: 'Меню',
    settings: 'Настройки',
    language: 'Язык',
    theme: 'Тема',
    themeLight: 'Светлая',
    themeDark: 'Темная',
    copyright: '© 2025 ME\'MOR. ВСЕ ПРАВА ЗАЩИЩЕНЫ.',
    pillarsTitle: 'ОСНОВНЫЕ СТОЛПЫ',
    ilmTitle: 'ОБИТЕЛЬ ЗНАНИЙ',
    ilmDesc: 'Сокровищница научных статей, видеоуроков и редких источников по архитектуре и искусству.',
    ilmLink: 'ВОЙТИ В БИБЛИОТЕКУ',
    amaliyotTitle: 'ПОЛЕ ПРАКТИКИ',
    amaliyotDesc: 'Реальные проекты, процессы строительства и современный взгляд на традиции наставничества.',
    amaliyotLink: 'СМОТРЕТЬ ПРОЕКТЫ',
    sanatTitle: 'ЦИФРОВОЕ ИСКУССТВО',
    sanatDesc: 'Векторные изображения национальных узоров, 3D-модели и современные элементы дизайна.',
    sanatLink: 'ПЕРЕЙТИ В ГАЛЕРЕЮ',
    aboutTitle: 'О ПЛАТФОРМЕ ME\'MOR',
    aboutP1: 'Наша цель — возродить забытые архитектурные традиции с помощью современных цифровых технологий и передать их будущим поколениям.',
    aboutP2: 'Здесь вы найдете не только теоретические знания, но и практический опыт, основанный на традициях «мастер-ученик».',
    teamTitle: 'КОМАНДА',
    teamDesc: 'Группа специалистов, работающих над платформой.',
    supportTitle: 'ПОДДЕРЖКА ПРОЕКТА',
    supportDesc: '«Me\'mor» — независимая платформа, которая живет благодаря поддержке таких любителей искусства, как вы.',
    supportFooter: 'Ваша помощь — вклад в сохранение нашей истории.',
    localCards: 'Быстрая и удобная помощь через местные карты (Uzcard, Humo).',
    intlCards: 'Помощь через международные карты (Visa, MasterCard).',
    sponsorButton: 'Стать спонсором',
    coffeeButton: 'Угостить кофе',
    back: 'Назад',
    notFound: 'Информация не найдена',
    ourTeam: 'Наша Команда',
    // Action
    actionTitle: 'Действие',
    actionDesc: 'От теории к практике. Наши проекты и планы на будущее.',
    events: 'Мероприятия',
    projects: 'Проекты',
    participate: 'Участвовать',
    // News
    latestNews: 'Последние новости',
    archive: 'Архив',
    readMoreNews: 'Читать далее',
    // Creations
    creationTitle: 'Творческие работы',
    creationDesc: 'Векторные узоры, концептуальные дизайны и цифровое искусство.',
    view: 'Смотреть',
    quote: '"Красота скрыта в деталях"',
    // Hadith
    hadithTitle: 'Достоинство знаний',
    sources: 'Источники',
    hadithClose: 'Закрыть',
    clickForFull: 'Нажмите для полного текста',
    prophetName: 'Пророк Мухаммад ﷺ',
    readMore: 'Подробнее',
    // Detail Labels
    description: 'Описание',
    technicalDrawing: 'Технический чертеж',
    materialTexture: 'Фактура материалов',
    specifications: 'Характеристики',
    start: 'Начало',
    type: 'Тип',
    scale: 'Масштаб',
    team: 'Команда',
    experts: 'Эксперт',
    downloadFiles: 'Скачать файлы',
    register: 'Регистрация',
    student: 'Ученик',
    experience: 'Опыт',
    share: 'ПОДЕЛИТЬСЯ',
    author: 'Автор',
    duration: 'Продолжительность',
    // Missing keys from Home.tsx
    harakatDesc: 'Реальные проекты, процессы строительства и современный взгляд на традиции наставничества.',
    ijodDesc: 'Векторные изображения национальных узоров, 3D-модели и современные элементы дизайна.',
    knowledgeTreasury: 'Сокровищница Знаний',
    allArticles: 'Все Статьи',
    project: 'Проект',
    artGallery: 'Художественная Галерея',
    viewAll: 'Смотреть Все',
    beautifyWorld: '"Dunyoni go\'zallashtirish uchun ..."',
    projectYear: 'ME\'MOR • 2025',
    teamMeeting: 'Встреча Команды',
    seoHome: 'Главная',
    seoKnowledge: 'Обитель Знаний',
    seoAction: 'Действие',
    seoCreation: 'Творческие работы',
    seoAbout: 'О нас',
    seoNews: 'Новости',
    seoContact: 'Контакты',
    seoSupport: 'Поддержка',
    seoSearch: 'Поиск',
    seoLogin: 'Вход',
    seoRegister: 'Регистрация',
    // SEO Specifics
    seoHomeTitle: 'Me\'mor - Платформа Узбекской Национальной Архитектуры',
    seoHomeDesc: 'Me\'mor — Платформа узбекской архитектуры, искусства и орнаментов. Сочетание исторического наследия и современных решений.',
    seoIlmTitle: 'Обитель Знаний - Статьи, Видео и Книги',
    seoIlmDesc: 'Коллекция научных ресурсов, видеоуроков и редких книг по архитектуре, искусству и истории на платформе Me\'mor.',
    seoHarakatTitle: 'Действие - Проекты и Мероприятия',
    seoHarakatDesc: 'Информация о проектах Me\'mor, строительных процессах и предстоящих культурных мероприятиях.',
    seoIjodTitle: 'Творчество - Галерея Искусств',
    seoIjodDesc: 'Слияние национального и современного искусства, векторные узоры, 3D-модели и творческие работы.',
    seoAboutTitle: 'О Платформе Me\'mor',
    seoAboutDesc: 'Узнайте о миссии, ценностях и команде, стоящей за проектом Me\'mor.',
    seoContactTitle: 'Контакты и Сотрудничество',
    seoContactDesc: 'Свяжитесь с командой Me\'mor для предложений о сотрудничестве и обратной связи.',
    seoNewsTitle: 'Новости и События',
    seoNewsDesc: 'Последние обновления платформы, новые ресурсы и важные объявления.',
    seoSupportTitle: 'Поддержать Проект',
    seoSupportDesc: 'Внесите свой вклад в развитие платформы Me\'mor и помогите сохранить наше национальное наследие.',
    seeMore: 'Подробнее'
  },
  tr: {
    ilm: 'İLİM',
    harakat: 'HAREKET',
    ijod: 'İCAD',
    about: 'Biz Haqimizda',
    news: 'Haberler',
    support: 'Destek',
    contact: 'İletişim',
    search: 'Arama',
    menu: 'Menü',
    settings: 'Ayarlar',
    language: 'Dil',
    theme: 'Tema',
    themeLight: 'Aydınlık',
    themeDark: 'Karanlık',
    copyright: '© 2025 ME\'MOR. TÜM HAKLARI SAKLIDIR.',
    pillarsTitle: 'TEMEL SÜTUNLAR',
    ilmTitle: 'İLİM KÖŞKÜ',
    ilmDesc: 'Mimarlık ve sanata dair bilimsel makaleler, video dersler ve nadir kaynakların toplandığı hazine.',
    ilmLink: 'KÜTÜPHANEYE GİRİŞ',
    amaliyotTitle: 'UYGULAMA ALANI',
    amaliyotDesc: 'Gerçek projeler, inşaat süreçleri ve usta-çırak geleneklerinin modern görünümü.',
    amaliyotLink: 'PROJELERİ GÖR',
    sanatTitle: 'DİJİTAL SANAT',
    sanatDesc: 'Milli motiflerin vektör çizimleri, 3D modeller ve modern tasarım öğeleri.',
    sanatLink: 'GALERİYE GİT',
    aboutTitle: 'ME\'MOR PLATFORMU HAKKINDA',
    aboutP1: 'Amacımız, unutulmakta olan mimari gelenekleri modern dijital teknolojiler aracılığıyla yeniden canlandırmak ve gelecek nesillere aktarmaktır.',
    aboutP2: 'Burada sadece teorik bilgi değil, usta-çırak geleneklerine dayalı pratik deneyimler de bulacaksınız.',
    teamTitle: 'EKİBİMİZ',
    teamDesc: 'Platform üzerinde çalışan uzman kadrosu.',
    supportTitle: 'PROJEYİ DESTEKLE',
    supportDesc: '"Me\'mor", sizin gibi sanatseverlerin desteğiyle yaşayan bağımsız bir platformdur.',
    supportFooter: 'Desteğiniz, tarihimizi korumaya yönelik bir katkıdır.',
    localCards: 'Yerel kartlar (Uzcard, Humo) aracılığıyla hızlı ve kolay destek.',
    intlCards: 'Uluslararası kartlar (Visa, MasterCard) aracılığıyla destek.',
    sponsorButton: 'Sponsor Ol',
    coffeeButton: 'Kahve Ismarla',
    back: 'Geri',
    notFound: 'Bilgi bulunamadı',
    ourTeam: 'Ekibimiz',
    // Action
    actionTitle: 'Hareket',
    actionDesc: 'Teoriden pratiğe. Projelerimiz ve gelecek planlarımız.',
    events: 'Etkinlikler',
    projects: 'Projeler',
    participate: 'Katıl',
    // News
    latestNews: 'Son Haberler',
    archive: 'Arşiv',
    readMoreNews: 'Devamını oku',
    // Creations
    creationTitle: 'Sanat Eserleri',
    creationDesc: 'Vektör desenler, kavramsal tasarımlar và dijital sanat.',
    view: 'Görüntüle',
    quote: '"Güzellik detaylarda gizlidir"',
    // Hadith
    hadithTitle: 'İlim Fazileti',
    sources: 'Kaynaklar',
    hadithClose: 'Kapat',
    clickForFull: 'Tam metin için tıklayın',
    prophetName: 'Peygamber ﷺ',
    readMore: 'Daha Fazla',
    // Detail Labels
    description: 'Açıklama',
    technicalDrawing: 'Teknik Çizim',
    materialTexture: 'Malzeme Dokusu',
    specifications: 'Özellikler',
    start: 'Başlangıç',
    type: 'Tür',
    scale: 'Hacim',
    team: 'Ekip',
    experts: 'Uzman',
    downloadFiles: 'Dosyaları indir',
    register: 'Kayıt Ol',
    student: 'Öğrenci',
    experience: 'Deneyim',
    share: 'PAYLAŞ',
    author: 'Yazar',
    duration: 'Süre',
    // Missing keys from Home.tsx
    harakatDesc: 'Gerçek projeler, inşaat süreçleri ve usta-çırak geleneklerinin modern görünümü.',
    ijodDesc: 'Milli motiflerin vektör çizimleri, 3D modeller ve modern tasarım öğeleri.',
    knowledgeTreasury: 'Bilgi Hazinesi',
    allArticles: 'Tüm Makaleler',
    project: 'Proje',
    artGallery: 'Sanat Galerisi',
    viewAll: 'Hepsini Gör',
    beautifyWorld: '"Dunyoni go\'zallashtirish uchun ..."',
    projectYear: 'ME\'MOR • 2025',
    teamMeeting: 'Ekip Toplantısı',
    seoHome: 'Ana Sayfa',
    seoKnowledge: 'İlim Köşkü',
    seoAction: 'Hareket',
    seoCreation: 'Sanat Eserleri',
    seoAbout: 'Hakkımızda',
    seoNews: 'Haberler',
    seoContact: 'İletişim',
    seoSupport: 'Destek',
    seoSearch: 'Arama',
    seoLogin: 'Giriş',
    seoRegister: 'Kayıt Ol',
    // SEO Specifics
    seoHomeTitle: 'Me\'mor - Özbek Ulusal Mimarlık Platformu',
    seoHomeDesc: 'Me\'mor — Özbek mimarisi, sanatı ve desenleri platformu. Tarihi miras ve modern çözümlerin uyumu.',
    seoIlmTitle: 'İlim Köşkü - Makaleler, Videolar ve Kitaplar',
    seoIlmDesc: 'Me\'mor platformunda mimarlık, sanat ve tarih üzerine bilimsel kaynaklar, video dersler ve nadir kitaplar koleksiyonu.',
    seoHarakatTitle: 'Hareket - Projeler ve Etkinlikler',
    seoHarakatDesc: 'Me\'mor projeleri, inşaat süreçleri ve yaklaşan kültürel etkinlikler hakkında bilgiler.',
    seoIjodTitle: 'İcad - Sanat Galerisi',
    seoIjodDesc: 'Ulusal ve modern sanatın buluşması, vektör desenler, 3D modeller ve yaratıcı çalışmalar.',
    seoAboutTitle: 'Me\'mor Platformu Hakkında',
    seoAboutDesc: 'Me\'mor projesinin misyonu, değerleri ve arkasındaki ekip hakkında bilgi edinin.',
    seoContactTitle: 'İletişim ve İşbirliği',
    seoContactDesc: 'İşbirliği teklifleri ve geri bildirim için Me\'mor ekibiyle iletişime geçin.',
    seoNewsTitle: 'Haberler ve Etkinlikler',
    seoNewsDesc: 'Platformdan en son güncellemeler, yeni eklenen kaynaklar ve önemli duyurular.',
    seoSupportTitle: 'Projeyi Destekle',
    seoSupportDesc: 'Me\'mor platformunun gelişimine katkıda bulunun ve ulusal mirasımızı korumaya yardımcı olun.',
    seeMore: 'Daha Fazla'
  }
};

export const NAV_ITEMS: NavItem[] = [
  { id: 'ilm', roman: 'I', label: 'ILM', subLabel: '(KNOWLEDGE)', route: PageRoute.KNOWLEDGE },
  { id: 'harakat', roman: 'II', label: 'HARAKAT', subLabel: '(ACTION)', route: PageRoute.ACTION },
  { id: 'ijod', roman: 'III', label: 'IJOD', subLabel: '(CREATION)', route: PageRoute.CREATION },
];

export const TEAM_MEMBERS: any[] = [
  { name: 'Otabek', role: 'Loyiha Asoschisi', image: 'https://memor.uz/people/otabek.jpg' },
  { name: 'Bunyod', role: 'Grafik Dizayner', image: 'https://memor.uz/people/bunyod.png' },
  { name: 'Biloliddin', role: 'Dasturchi', image: 'https://memor.uz/people/biloliddin.jpg' },
  { name: 'Zuhra', role: 'Dizayner', image: 'https://memor.uz/people/zuhra.png' },
  { name: 'Jasmina', role: 'Creativ Partner', image: 'https://memor.uz/people/jasmina.png' },
  { name: 'Aminaxon', role: 'Kontent Menejeri', image: 'https://memor.uz/people/aminaxon.png' },
];
